
const I18N={pl:{Home:'Strona główna',Bikes:'Rowery','E-Bikes':'Rowery elektryczne',About:'O nas',Contact:'Kontakt','View details':'Zobacz szczegóły','Add to basket':'Dodaj do koszyka',Basket:'Koszyk',Total:'Razem','Continue on WhatsApp':'Kontynuuj na WhatsApp','Your basket is empty.':'Twój koszyk jest pusty.',Remove:'Usuń','Collection & delivery':'Odbiór i dostawa','Condition':'Stan','Specification':'Specyfikacja','Available':'Dostępny','Good Price':'Dobra cena','Hot Offer':'Gorąca oferta','Ready to ride':'Gotowy do jazdy','Overall':'Ogólny','Mechanical':'Mechaniczny','Cosmetic':'Wizualny','Collection in Swindon or Marlborough. Local delivery within 30 miles.':'Odbiór w Swindon lub Marlborough. Dostawa lokalna do 30 mil.'}};
function t(s){const l=localStorage.getItem('tomybike-language')||'en';return l==='pl'?(I18N.pl[s]||s):s}
function cart(){try{return JSON.parse(localStorage.getItem('tomybike-cart')||'[]')}catch{return[]}}
function saveCart(c){localStorage.setItem('tomybike-cart',JSON.stringify(c));updateCartCount()}
function updateCartCount(){document.querySelectorAll('[data-cart-count]').forEach(x=>x.textContent=cart().length)}
function addToCart(id){const p=PRODUCTS.find(x=>x.id===id);const c=cart();if(!c.some(x=>x.id===id))c.push({id:p.id,name:p.name,price:p.price});saveCart(c);openCart()}
function removeFromCart(i){const c=cart();c.splice(i,1);saveCart(c);renderCart()}
function renderCart(){const c=cart(),box=document.getElementById('cartItems'),total=document.getElementById('cartTotal'),wa=document.getElementById('cartWA');if(!box)return;if(!c.length){box.innerHTML='<p>'+t('Your basket is empty.')+'</p>';total.textContent='£0';wa.href='#';return}box.innerHTML=c.map((x,i)=>`<div class="cart-item"><b>${x.name}</b><div>£${x.price}</div><button class="btn" onclick="removeFromCart(${i})">${t('Remove')}</button></div>`).join('');const sum=c.reduce((s,x)=>s+x.price,0);total.textContent='£'+sum;wa.href='https://wa.me/447459620789?text='+encodeURIComponent('Hello, I am interested in:
'+c.map(x=>`${x.name} - £${x.price}`).join('
'))}
function openMenu(){document.getElementById('navDrawer').classList.add('open');document.getElementById('overlay').classList.add('open')}
function openCart(){renderCart();document.getElementById('cartDrawer').classList.add('open');document.getElementById('overlay').classList.add('open')}
function closeDrawers(){document.querySelectorAll('.drawer').forEach(x=>x.classList.remove('open'));document.getElementById('overlay').classList.remove('open')}
function shell(){return `<div id="overlay" class="overlay" onclick="closeDrawers()"></div><aside id="navDrawer" class="drawer nav-drawer"><button class="close" onclick="closeDrawers()">×</button><nav><a href="index.html">${t('Home')}</a><a href="index.html#bikes">${t('Bikes')}</a><a href="index.html#ebikes">${t('E-Bikes')}</a><a href="index.html#about">${t('About')}</a><a href="index.html#contact">${t('Contact')}</a></nav></aside><aside id="cartDrawer" class="drawer cart-drawer"><button class="close" onclick="closeDrawers()">×</button><h2>${t('Basket')}</h2><div id="cartItems"></div><div class="price">${t('Total')}: <span id="cartTotal">£0</span></div><a id="cartWA" class="btn primary" href="#">${t('Continue on WhatsApp')}</a></aside>`}
function header(){return `<header class="site-header"><div class="wrap header-inner"><button class="menu-btn" onclick="openMenu()">☰</button><a href="index.html"><img class="logo" src="assets/my-bike-clean-logo.png" alt="My Bike"></a><nav class="nav"><a href="index.html">${t('Home')}</a><a href="index.html#bikes">${t('Bikes')}</a><a href="index.html#ebikes">${t('E-Bikes')}</a><a href="index.html#about">${t('About')}</a><a href="index.html#contact">${t('Contact')}</a></nav><div class="header-tools"><select class="lang" onchange="localStorage.setItem('tomybike-language',this.value);location.reload()"><option value="en">English</option><option value="pl">Polski</option></select><a href="#" class="cart-btn" onclick="openCart();return false">🛒<span class="count" data-cart-count>0</span></a></div></div></header>`}
function initCommon(){document.body.insertAdjacentHTML('afterbegin',header());document.body.insertAdjacentHTML('beforeend',shell());document.querySelector('.lang').value=localStorage.getItem('tomybike-language')||'en';updateCartCount()}
