window.TOMYBIKE_PRODUCTS = [
  {
    id: "trek-domane-al-3",
    status: "available",
    category: "road",
    typeEn: "Road endurance bike",
    typePl: "Szosowy rower endurance",
    name: "Trek Domane AL 3",
    price: 465,
    metaEn: "2023 • Lithium Grey • 49 cm / Small",
    metaPl: "2023 • Lithium Grey • 49 cm / Mały",
    size: "S",
    sizeLabel: "49 cm / Small",
    heightEn: "Approx. 155–165 cm",
    heightPl: "Około 155–165 cm",
    wheel: "700c",
    colourEn: "Lithium Grey",
    colourPl: "Lithium Grey",
    overall: 8,
    mechanical: 9,
    cosmetic: 7,
    shortEn: "Comfortable aluminium endurance road bike with carbon fork and Shimano Sora 2×9 drivetrain.",
    shortPl: "Wygodny aluminiowy rower szosowy endurance z karbonowym widelcem i napędem Shimano Sora 2×9.",
    conditionEn: "Good clean used condition. Minor cosmetic marks consistent with normal use. Please see all photographs.",
    conditionPl: "Dobry, czysty stan używany. Drobne ślady wizualne zgodne z normalnym użytkowaniem. Proszę obejrzeć wszystkie zdjęcia.",
    specs: [
      ["Brand", "Marka", "Trek"],
      ["Model", "Model", "Domane AL 3"],
      ["Year", "Rok", "2023"],
      ["Frame", "Rama", "100 Series Alpha Aluminium"],
      ["Fork", "Widelec", "Carbon"],
      ["Groupset", "Osprzęt", "Shimano Sora"],
      ["Gears", "Biegi", "2 × 9 speed"],
      ["Brakes", "Hamulce", "Tektro mechanical disc"],
      ["Wheel size", "Rozmiar kół", "700c"],
      ["Frame size", "Rozmiar ramy", "49 cm / Small"],
      ["Recommended rider height", "Zalecany wzrost użytkownika", "Approx. 155–165 cm"],
      ["Colour", "Kolor", "Lithium Grey"]
    ],
    images: [
      "assets/trek-domane-al3-01.jpeg","assets/trek-domane-al3-02.jpeg","assets/trek-domane-al3-03.jpeg",
      "assets/trek-domane-al3-04.jpeg","assets/trek-domane-al3-05.jpeg","assets/trek-domane-al3-06.jpeg",
      "assets/trek-domane-al3-07.jpeg","assets/trek-domane-al3-08.jpeg","assets/trek-domane-al3-09.jpeg",
      "assets/trek-domane-al3-10.jpeg"
    ]
  },
  {
    id: "scott-e-genius-910",
    status: "available",
    category: "electric",
    typeEn: "Electric full-suspension MTB",
    typePl: "Elektryczny MTB z pełnym zawieszeniem",
    name: "Scott E-Genius 910",
    price: 990,
    metaEn: "Bosch • Black / Green • XL / 29er",
    metaPl: "Bosch • Czarny / zielony • XL / 29 cali",
    size: "XL",
    sizeLabel: "XL",
    heightEn: "Approx. 185–200 cm",
    heightPl: "Około 185–200 cm",
    wheel: "29”",
    colourEn: "Black / Green",
    colourPl: "Czarny / zielony",
    overall: 9,
    mechanical: 9,
    cosmetic: 8,
    shortEn: "Powerful Bosch electric full-suspension mountain bike with FOX suspension and Shimano XT/SLX drivetrain.",
    shortPl: "Mocny elektryczny rower górski Bosch z pełnym zawieszeniem FOX i napędem Shimano XT/SLX.",
    conditionEn: "Good clean used condition with minor marks consistent with normal use. Original Bosch charger included. Battery keys are not included.",
    conditionPl: "Dobry, czysty stan używany z drobnymi śladami normalnego użytkowania. Oryginalna ładowarka Bosch w zestawie. Brak kluczyków do baterii.",
    specs: [
      ["Brand", "Marka", "Scott"],
      ["Model", "Model", "E-Genius 910"],
      ["Bike type", "Typ roweru", "Electric full-suspension MTB"],
      ["Frame", "Rama", "Aluminium, size XL"],
      ["Motor", "Silnik", "Bosch Performance Line CX"],
      ["Battery", "Bateria", "Bosch PowerPack 500"],
      ["Charger", "Ładowarka", "Original Bosch charger included"],
      ["Front suspension", "Przednie zawieszenie", "FOX 34"],
      ["Rear suspension", "Tylne zawieszenie", "FOX Nude"],
      ["Drivetrain", "Napęd", "Shimano XT / SLX"],
      ["Brakes", "Hamulce", "Shimano hydraulic disc"],
      ["Wheel size", "Rozmiar kół", "29 inches"],
      ["Frame size", "Rozmiar ramy", "XL"],
      ["Recommended rider height", "Zalecany wzrost użytkownika", "Approx. 185–200 cm"],
      ["Colour", "Kolor", "Black / Green"],
      ["Battery keys", "Kluczyki do baterii", "Not included"]
    ],
    images: [
      "assets/scott-egenius-910-01.jpeg","assets/scott-egenius-910-02.jpeg","assets/scott-egenius-910-03.jpeg",
      "assets/scott-egenius-910-04.jpeg","assets/scott-egenius-910-05.jpeg","assets/scott-egenius-910-06.jpeg",
      "assets/scott-egenius-910-07.jpeg","assets/scott-egenius-910-08.jpeg","assets/scott-egenius-910-09.jpeg",
      "assets/scott-egenius-910-10.jpeg"
    ]
  }
];
